### ISSUE TITLE
Feature request: Changelog.md

### ISSUE THREAD

**Issue by aaarichter** [groupon/testium#139]
:-) it would help to see what has changed ;-)

**Comment by EndangeredMassa** [comment]
You can see a list of changes in the [Releases](https://github.com/groupon-testium/testium/releases) section. However, I agree that an in-repo CHANGELOG.md would be great as well.

I've been working on a different tool that will make it easy to do both of these and keep them in sync, called [npub](https://github.com/EndangeredMassa/npub).

**Comment by aaarichter** [comment]
cool :+1:

**Comment by jkrems** [comment]
Guessing this means the issue can be closed. Feel free to open if this is still an issue! :)
