### ISSUE TITLE
Add ES6-friendly mocha API

### ISSUE THREAD

**Issue by jkrems** [groupon/testium#158]
ES6 arrow functions use lexical `this` which makes injecting the browser into the test context awkward and possibly forces people to use old-style functions. We should offer an interface that does not depend on the test context / `this`.

One example for a possible interface, using two new named exports:

```js
import { browser, setupBrowser } from 'testium/mocha';

describe('A test', () => {
  before(setupBrowser());
  it('can use the browser', () => {
    browser.navigateTo('/some/url');
  });
});
```

Usage from coffee-script:

```js
{ browser, setupBrowser } = require 'testium/mocha';

describe 'A test', ->
  before setupBrowser()

  it 'can use the browser', ->
    browser.navigateTo '/some/url'
```

This could be achieved as a non-breaking change by maintaining the current default export (as a combination of `setupBrowser` and `this.browser = browser`).

**Comment by EndangeredMassa** [comment]
I actually prefer this proposed interface regardless of ES6's limitations. Making it backwards compatible is great.

Should `setupBrowser` be a function call to accept optional options in order to match `injectBrowser`? Or, we would essentially be deprecating that functionality?

Should use of `injectBrowser` be deprecated and removed in 4.0? We could probably just leave it around without much trouble.

**Comment by jkrems** [comment]
I think keeping the default export around makes sense. Should be pretty low maintenance as long as the semantics are defined in terms of `browser`/`setupBrowser`.

About the `setupBrowser` options - that's a good question. I'm still on the fence over the cookie clearing behavior and the session vs. connection thing. For for this it might be best to focus on the change in interface, e.g. keep `setupBrowser` as `Options => Fn(cb)`. Updating the description to clarify that.

**Comment by EndangeredMassa** [comment]
Sounds good to me.

**Comment by jkrems** [comment]
Now supported like this:

```js
import { browser } from 'testium/mocha';

describe('A test', () => {
  before(browser.beforeHook());

  it('can use the browser', () => {
    browser.navigateTo('/some/url');
  });
});
```
