### ISSUE TITLE
Add injectBrowser configuration support to .testiumrc

### ISSUE THREAD

**Issue by felipebrahm** [groupon/testium#163]
By default, `reuseSession` and `keepCookies` are set to `true` unless you pass in an option to `injectBrowser` on every test file. I think for most projects it would make sense to have the opposite defaults (do not reuse session nor cookies) to avoid test flakiness and so that no test file depends on the state of the previous file.

Also, in case it helps with debugging, replacing `injectBrowser()` with `injectBrowser({ reuseSession: false, keepCookies: false })` in all of our tests helped reduce the number of times we see this error message: `Request connection timed out after 2000ms to: http://127.0.0.1:57427/wd/hub/session/00c48300-37be-11e5-83fb-0081b423cc00/url`, which we were seeing pretty often, specially in tests which involved setting or clearing cookies.

**Comment by EndangeredMassa** [comment]
It sounds pretty reasonable to turn `keepCookies` off by default. I'm not sure about `reuseSession`, though. I'd want to see the difference in performance that might cause.

Were you able to track down that common error to one or the other of these options?

**Comment by felipebrahm** [comment]
@EndangeredMassa I realized later that `keepCookies` is actually `false` by default, so that change didn't really do much. But after adding `reuseSession: false`, my CI build is passing most of the time and I haven't run into the session error anymore (`Request connection timed out after 2000ms to: http://127.0.0.1:57427/wd/hub/session/00c48300-37be-11e5-83fb-0081b423cc00/url`). The thing is, this is kind of a workaround. The real problem is *why* are there some instances when testium fails to grab a browser session? Why is the session dying? Maybe a fix (although also a *workaround*) would be that when testium can't get the session instead of throwing a timeout error, it could try to initiate a new session instead.

**Comment by EndangeredMassa** [comment]
Unfortunately, that error quite often means that the app under test didn't respond within the timeout. If that's not the case when you see the error, then it can now mean both things. I'm not sure how we could make sure that we are seeing one issue or the other, which we need to do in order to retry with a new session.
