### ISSUE TITLE
Documentation on Element missing? + Mocha link in readme broken

### ISSUE THREAD

**Issue by aaarichter** [groupon/testium#176]
Hi,

I ran `console.log el = browser.getElement('cssSelector')` and got the following output

```
Element {
  inspect: [Function],
  get: [Function],
  getElement: [Function],
  getElements: [Function],
  getLocation: [Function],
  getLocationInView: [Function],
  getSize: [Function],
  isVisible: [Function],
  click: [Function],
  type: [Function],
  clear: [Function] }
```

From this list only `get(), click(), isVisible(), type(), clear()`  are documented.

-------------------------

The MochaJs link http://mochajs.org/mocha/ in the readme.md is broken.

**Comment by EndangeredMassa** [comment]
Thanks for taking the time to report this error! We'll fix it soon.

**Comment by EndangeredMassa** [comment]
Updated here: https://github.com/groupon/testium/pull/177
