### ISSUE TITLE
Do something on timeout, before failing the test

### ISSUE THREAD

**Issue by katylava** [groupon/testium#189]
It's tough to debug failures due to timeouts. Would be easier if we could hook into that process and do something, like grab a screenshot, before the test fails.

Example: 

```
function onTimeout(done) {
    console.log(browser.getConsoleLogs());
    done();
}

browser.waitForUrl('/path', 10000, onTimeout);
```

**Comment by jkrems** [comment]
Thanks for the suggestion & sorry for not responding earlier! At least for some browsers (e.g. phantomjs) the console logs are already part of the log file and our mocha integration does screenshots on failure. Would it help if we marked timeout errors in a way that is easier to catch? E.g.:

```js
browser.waitForUrl('/path', 10000)
  .catch(TestiumTimeoutError, handleTimeoutError);

try {
  browser.waitForUrl('/path', 10000);
} catch (err) {
  if (err instanceof TestiumTimeoutError) { handleTimeoutError(err); }
  else { throw err; }
}
```

It seems like a good idea to generally dump the console logs to the output (together with the link to the screenshot) on failure.

**Comment by katylava** [comment]
Ah, I don't get screenshots for every error, but if I'm supposed to, then something else is wrong. 

It's funny, I use the try/catch pattern in Node.js very rarely, so it didn't occur to me that I could do that here. I feel dumb now. That said, making it easier to catch would definitely improve readability. Test code gets so noisy as it is.

**Comment by jkrems** [comment]
Maybe you're using a reporter like `tap` that blocks stdout logs. You can check `test/log/failed_screenshosts` (or similar) in your app. Maybe the screenshots are actually already there. It sounds like for now the `try/catch` did the trick.
