### ISSUE TITLE
Can't get <title> tag using getElement or browser assertions

### ISSUE THREAD

**Issue by seifertd** [groupon/testium#192]
Writing a test against title tag content, always get null tag text for the following:

```
browser.assert.elementHasText("title", /some regex here/) // always compares regex against empty string
var titleTag = browser.getElement("title")
var assert = require('assertive')
assert.match(/some regex here/, titleTag.get("text")); // get("text") always returns null
```
A work around exists, however, so this is low priority:
```coffeescript
titleTagContent = @browser.evaluate ->
   // Assuming jquery is on the page
   $('title').text()

assert.match /some regex here/, titleTagContent
```

**Comment by jkrems** [comment]
Normally I would expect that `browser.getPageTitle()` would be used. Is there a reason why you use the `title` selector? I could imagine that the selectors outside of the body don't work correctly.

**Comment by seifertd** [comment]
getPageTitle works as expected, so this is user error, closing
