### ISSUE TITLE
switch to first-class proxy

### ISSUE THREAD

**Issue by EndangeredMassa** [groupon/testium#91]
Testium inserts a custom proxy between selenium and your app. This provides several features, but is also the source of complexity that has caused bugs in the past.

I would like to swap this out for a premade solution that can accomplish the same thing. That would allow us to have even more features, like capturing HAR files, etc. After looking around, [browsermob](http://bmp.lightbody.net/) looks like the best option.

The proxy needs to:
- strip cache headers
- mark new page requests (to differentiate between resource requests)
- auto respond success on first page load
- store response headers and status code in a special cookie (or some other mechanism)
- force actual response codes >= 400 to be 200

**Comment by jkrems** [comment]
Initial work: https://github.com/testiumjs/testium-core/pull/19
